from enum import Enum

class NotificationType(Enum):
  ADOPTION_REQUEST =  'ADOPTION_REQUEST'
  ADOPTION_STATUS_UPDATE = 'ADOPTION_STATUS_UPDATE'
  ADD_DONATION = 'ADD_DONATION'
  DONATION_STATUS_UPDATE = 'DONATION_STATUS_UPDATE'