from enum import Enum

class NotificationType(Enum):
  ADOPTION_REQUEST =  'ADOPTION_REQUEST'
  ADOPTION_STATUS_UPDATE = 'ADOPTION_STATUS_UPDATE'
  ADD_DONATION_MONEY = 'ADD_DONATION_MONEY'
  ADD_DONATION_IN_KIND = 'ADD_DONATION_IN_KIND'
  DONATION_STATUS_UPDATE = 'DONATION_STATUS_UPDATE'
  EVENT_INVITED = 'EVENT_INVITED'